In [1]:
%load_ext rpy2.ipython

## **📘 Practical–17**

**Creating and Manipulating Objects**

- Work with vectors, matrices, lists, and data frames

- **Experiment:** Create a data frame and display

  - Structure

   - Statistical summary

  - Nature (type) of data

#### 1️⃣ Create Vector

In [12]:
%%R

numbers <- c(10, 20, 30, 40, 50)

print(numbers)

[1] 10 20 30 40 50


#### 2️⃣ Create Matrix

In [13]:
%%R

mat <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3)

print(mat)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


#### 3️⃣ Create List

In [14]:
%%R

my_list <- list(name = "Suraj", age = 21, marks = c(80, 85, 90))

print(my_list)

$name
[1] "Suraj"

$age
[1] 21

$marks
[1] 80 85 90



#### 4️⃣ Create Data Frame

In [15]:
%%R

student_data <- data.frame(
        Name = c("Suraj", "Ashish", "Kamlesh", "Ravi"),
        Age = c(20, 21, 19, 22),
        Marks = c(75, 80, 85, 90)
)

print(student_data)

     Name Age Marks
1   Suraj  20    75
2  Ashish  21    80
3 Kamlesh  19    85
4    Ravi  22    90


#### 5️⃣ Display Structure

In [16]:
%%R

str(student_data)

'data.frame':	4 obs. of  3 variables:
 $ Name : chr  "Suraj" "Ashish" "Kamlesh" "Ravi"
 $ Age  : num  20 21 19 22
 $ Marks: num  75 80 85 90


#### 6️⃣ Statistical Summary

In [17]:
%%R

summary(student_data)

     Name                Age            Marks      
 Length:4           Min.   :19.00   Min.   :75.00  
 Class :character   1st Qu.:19.75   1st Qu.:78.75  
 Mode  :character   Median :20.50   Median :82.50  
                    Mean   :20.50   Mean   :82.50  
                    3rd Qu.:21.25   3rd Qu.:86.25  
                    Max.   :22.00   Max.   :90.00  


#### 7️⃣ Nature (Type) of Data

In [18]:
%%R

sapply(student_data, class)

       Name         Age       Marks 
"character"   "numeric"   "numeric" 


## **📘 Practical–18**

**Indexing and Accessing Object Values**

- Demonstrate indexing systems for R objects

- Experiment:

  **1.** Extract sub-matrix whose rows have column value > 3

  **2.** Convert a matrix to a 1-dimensional array

#### 1️⃣ Create  Matrix

In [19]:
%%R

mat <- matrix(c(1,2,3,4,5,6,7,8,9), nrow = 3, byrow = TRUE)

# Display matrix
print(mat)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


#### 🔹 **Experiment 1**
- Extract sub-matrix whose column value > 3

In [20]:
%%R

# Select rows where 2nd column > 3
result <- mat[mat[,2] > 3, ]

# Display result
print(result)

     [,1] [,2] [,3]
[1,]    4    5    6
[2,]    7    8    9


#### 🔹 **Experiment 2**
- Convert matrix to 1D array

In [21]:
%%R

# Convert matrix to 1D array
new <- as.vector(mat)

# Display result
print(new)

[1] 1 4 7 2 5 8 3 6 9
